Добавил моки и отрисовку фотографий
Yougn/1138711-kekstagram-20 pull request #1
Opened 2020-10-06 13:53 UTC by Yougn

2020-10-06 14:34 UTC, balesniy requested changes

2020-10-06 14:34 UTC, balesniy commented on .eslintrc
> +  "htmlacademy/es5/es6"
тут нужно что то одно оставить

2020-10-06 14:34 UTC, balesniy commented on js/main.js
> +  var maxNumber = 10;
у нас уже есть COMMENTS_NUMBER, а вообще константы капсом и просят выносить из функций

2020-10-06 14:34 UTC, balesniy commented on js/main.js
> +  var commentsList = [];
массивы нужно назвать во множественном числе

2020-10-06 14:34 UTC, balesniy commented on js/main.js
> +  return commentsList.slice(0, getRandomInteger(1, maxNumber));
лишняя операция, можно в цикле ограничить число итераций вместо COMMENTS_NUMBER

2020-10-06 14:34 UTC, balesniy commented on js/main.js
> +var getObject = function (number) {
функции нужно наглядное имя

2020-10-06 14:34 UTC, balesniy commented on js/main.js
> +  var blocks = [];
переменной нужно дать наглядное имя

2020-10-06 14:56 UTC, Yougn commented on .eslintrc
> +  "htmlacademy/es5/es6"
Исправлено

2020-10-06 14:59 UTC, Yougn commented on js/main.js
> +  var maxNumber = 10;
Исправлено

2020-10-06 15:00 UTC, Yougn commented on js/main.js
> +  var commentsList = [];
Исправлено

2020-10-06 15:09 UTC, Yougn commented on js/main.js
> +var getObject = function (number) {
Исправлено

2020-10-06 15:12 UTC, Yougn commented on js/main.js
> +  var blocks = [];
Исправлено

2020-10-06 15:25 UTC, Yougn commented on js/main.js
> +  return commentsList.slice(0, getRandomInteger(1, maxNumber));
Вроде исправлено

2020-10-06 17:07 UTC, merged

2020-10-06 19:04 UTC, balesniy commented on js/main.js
> +  var commentsLists = [];
это не "списки", тут лучше использовать comments

2020-10-06 19:04 UTC, balesniy commented on js/main.js
> +  var randomNumber = getRandomInteger(1,NUMBER)
линтер просит пробелы

2020-10-07 05:42 UTC, Yougn commented on js/main.js
> +  var randomNumber = getRandomInteger(1,NUMBER)
Исправлено

2020-10-07 05:43 UTC, Yougn commented on js/main.js
> +  var commentsLists = [];
Исправлено