Добавил отрисовку главной карточки
Yougn/1138711-kekstagram-20 pull request #2
Opened 2020-10-07 05:52 UTC by Yougn

2020-10-07 12:58 UTC, balesniy requested changes

2020-10-07 12:58 UTC, balesniy commented on js/main.js
> +var renderBigPicture = function (photos) {
в параметр приходит одна фотка - photo - множественное число оставь для массивов

2020-10-07 12:58 UTC, balesniy commented on js/main.js
> +
перед отрисовкой комментов, нужно почистись контейнер

2020-10-07 12:58 UTC, balesniy commented on js/main.js
> +      for (var j = 2; j < photos.comments.length; j++) {
достаточно одного цикла по comments, в нем создаем и li и img

2020-10-07 12:58 UTC, balesniy commented on js/main.js
> +      pictureComments.appendChild(newElement);
множественную вставку нужно сделать через fragment

2020-10-07 12:58 UTC, balesniy commented on js/main.js
> +var commentCount = document.querySelector('.social__comment-count');
этот код нужно перенести в renderBigPicture

2020-10-08 05:34 UTC, Yougn commented on js/main.js
> +var renderBigPicture = function (photos) {
Исправлено

2020-10-08 05:41 UTC, Yougn commented on js/main.js
> +
Исправлено

2020-10-08 07:46 UTC, Yougn commented on js/main.js
> +var commentCount = document.querySelector('.social__comment-count');
Исправлено

2020-10-08 07:46 UTC, Yougn commented on js/main.js
> +      for (var j = 2; j < photos.comments.length; j++) {
Вроде исправлено

2020-10-08 09:11 UTC, Yougn commented on js/main.js
> +      pictureComments.appendChild(newElement);
Исправлено

2020-10-08 12:34 UTC, balesniy requested changes

2020-10-08 12:34 UTC, balesniy commented on js/main.js
> +var photo = getObjectsList(NUMBER);
массивы нужно назвать во множественном числе, чтобы не путать их с объектами

2020-10-08 12:34 UTC, balesniy commented on js/main.js
> +var createFragment = function (photo) {
массивы - photos

2020-10-11 13:48 UTC, merged

2020-10-11 13:54 UTC, Yougn commented on js/main.js
> +var createFragment = function (photo) {
Исправлено

2020-10-11 13:54 UTC, Yougn commented on js/main.js
> +var photo = getObjectsList(NUMBER);
Исправлено