добавил форму
Yougn/1138711-kekstagram-20 pull request #3
Opened 2020-10-15 17:41 UTC by Yougn

2020-10-16 08:15 UTC, balesniy requested changes

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +  formImage.classList.remove('hidden');
при открытии нужно добавить класс на body и обработчик на документ, и снять их при закрытии

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +  uploadFile.value = '';
при закрытии еще нужно сбросить масштаб и фильтры, почистить форму

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +document.addEventListener('keydown', function (evt) {
анонимный обработчик будет не снять

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +  if (evt.key === 'Escape') {
нужна проверка на то что курсор не находится в поле ввода

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +var changeEffectInput = function () {
эта функция не записывает уровень, только переменную levelValue, нужно явно задать значение в value

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    var filterChrome = document.querySelector('.effects__preview--chrome')
лишний поиск по селектору, элемент уже есть в pictureFilter

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    filterHeat.style.filter = 'brightness(' + getLevelEffect() / 100 * 3 + ')';
яркость по заданию от 1, нужно добавить минимальное значение, как в получении случайного целого делали

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +  for (var i = 0; i < radioFilter.length; i++) {
мы используем evt.target - одинаковые обработчики лишние, достаточно одного на общий контейнер, посмотри демку про делегирование событий

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +      if (pictureFilter.classList.length > 2) {
у нас есть критерий про точечные изменения, в нем хороший пример как можно оптимально решить эту задачу

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +var changeFilterPicture = function () {
название функции не отражает ее действие, она не меняет фильтр, а устанавливает обработчик

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +var changePictureSize = function () {
тут тоже нужно более наглядное название

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    } else { return MAX_SIZE + "%" }
лишний else

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +  for (var i = 0; i < textLists.length; i++) {
перед проверкой каждого тега нужно проверить их кол-во

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +  var arrayHashtags = [];
массивы просят назвать во множественном числе

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    if (textLists.length > 5) {
5 в константы

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    validHashtag(textLists[i]);
если нашли ошибку, то дальше можно не проверять, цикл нужно остановить

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +textHashtags.addEventListener('input', function () {
еще нужно провалидировать длину коммента и тип файла

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    if (!textHashtagsValue.includes('#')) {
проверка не сработает если хэш внутри тега, нам нужен именно первый символ

2020-10-16 08:15 UTC, balesniy commented on js/main.js
> +    } else if (!textHashtagsValue.match(/(^#[a-zA-Zа-яА-Я0-9]*$)/g)) {
match тут не подходит, лучше test

2020-10-18 12:14 UTC, Yougn commented on js/main.js
> +  formImage.classList.remove('hidden');
Исправлено

2020-10-18 18:29 UTC, Yougn commented on js/main.js
> +document.addEventListener('keydown', function (evt) {
Исправлено

2020-10-18 18:50 UTC, Yougn commented on js/main.js
> +  uploadFile.value = '';
Исправлено

2020-10-19 09:18 UTC, Yougn commented on js/main.js
> +  if (evt.key === 'Escape') {
Исправлено

2020-10-19 09:46 UTC, Yougn commented on js/main.js
> +var changeEffectInput = function () {
Исправлено

2020-10-19 10:02 UTC, Yougn commented on js/main.js
> +    var filterChrome = document.querySelector('.effects__preview--chrome')
Исправлено

2020-10-19 10:08 UTC, Yougn commented on js/main.js
> +    filterHeat.style.filter = 'brightness(' + getLevelEffect() / 100 * 3 + ')';
Исправлено

2020-10-19 12:50 UTC, Yougn commented on js/main.js
> +  for (var i = 0; i < radioFilter.length; i++) {
Исправлено

2020-10-19 14:07 UTC, Yougn commented on js/main.js
> +      if (pictureFilter.classList.length > 2) {
Исправлено

2020-10-19 14:10 UTC, Yougn commented on js/main.js
> +var changeFilterPicture = function () {
Исправлено

2020-10-19 14:18 UTC, Yougn commented on js/main.js
> +var changePictureSize = function () {
Исправлено *)

2020-10-19 14:19 UTC, Yougn commented on js/main.js
> +    } else { return MAX_SIZE + "%" }
Исправлено

2020-10-19 14:20 UTC, Yougn commented on js/main.js
> +  var arrayHashtags = [];
Исправлено

2020-10-19 14:57 UTC, Yougn commented on js/main.js
> +  for (var i = 0; i < textLists.length; i++) {
Вроде исправил

2020-10-19 14:59 UTC, Yougn commented on js/main.js
> +    if (textLists.length > 5) {
Исправлено

2020-10-19 15:09 UTC, Yougn commented on js/main.js
> +    validHashtag(textLists[i]);
Исправлено

2020-10-19 15:09 UTC, Yougn commented on js/main.js
> +    if (!textHashtagsValue.includes('#')) {
Исправлено

2020-10-19 15:42 UTC, Yougn commented on js/main.js
> +textHashtags.addEventListener('input', function () {
Исправлено

2020-10-19 16:19 UTC, Yougn commented on js/main.js
> +    } else if (!textHashtagsValue.match(/(^#[a-zA-Zа-яА-Я0-9]*$)/g)) {
Исправлено

2020-10-19 17:44 UTC, balesniy requested changes

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  var body = document.querySelector('body');
вынеси поиск body из функций

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  var formImage = document.querySelector('.img-upload__overlay');
и тут лишний поиск formImage

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    pictureFilter.classList.remove('effects__preview--chrome')
кроме класса еще нужно сбросить style.filter

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    pictureFilter.style.filter = 'brightness(' + getRandomInteger(MIN_BRIGHTNESS, MAX_BRIGHTNESS) + ')';
слйчайное число тут не подойдет, нам нужно взять getLevelEffect и скорректировать его на MIN_BRIGHTNESS

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    pictureFilter.style.filter = 'blur(' + getLevelEffect() / 100 * 3 + 'px)';
3 в константы

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  var newFilter = pictureFilter.classList.item(1);
там могут быть еще классы и все сломается, запиши в текущий choise

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +
тут еще нужна проверка на none и вызов closeSlider по условию

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  if (pictureFilter.classList.contains('effects__preview--chrome')) {
у нас есть currentFilter, проверки лишние

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    var number = parseInt(fieldControl.value, 10);
текущее значение уже записано в fieldControlValue, лишнее преобразование

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    if (!textHashtagsValue[0].includes('#')) {
лишний includes для проверки одного символа

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    } else if (!textHashtagsValue.match(/(^#[a-zA-Zа-яА-Я0-9]*$)/g)) {
не исправлено)

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  var textLists = textHashtagsValue.toLowerCase().split(' ');
получилось "списки текста" - переменной нужно более наглядное имя

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  var arraysHashtags = [];
массивы тегов? - нужно более наглядное имя

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +  for (var i = 0; i < textListsNumber; i++) {
перед проверкой каждого тега, нужно проверить их количество

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    if (textListsNumber > NUMBER_HASHTAGS) {
проверку на количество нужно вынести из цикла

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +      textHashtags.setCustomValidity('Один и тот же хэш-тег не может быть использован дважды');
если тег повторяется, цикл нужно остановить, дальше можно не проверять

2020-10-19 17:44 UTC, balesniy commented on js/main.js
> +    var isHashtagValid = validHashtag(textListsNumber[i]);
textListsNumber это число, не массив, массив это textLists

2020-10-20 09:42 UTC, Yougn commented on js/main.js
> +    } else if (!textHashtagsValue.match(/(^#[a-zA-Zа-яА-Я0-9]*$)/g)) {
вот теперь хорошо

2020-10-20 09:43 UTC, Yougn commented on js/main.js
> +  var body = document.querySelector('body');
Исправлено

2020-10-20 09:45 UTC, Yougn commented on js/main.js
> +  var formImage = document.querySelector('.img-upload__overlay');
Исправлено

2020-10-20 09:56 UTC, Yougn commented on js/main.js
> +    pictureFilter.classList.remove('effects__preview--chrome')
Исправлено

2020-10-20 10:17 UTC, Yougn commented on js/main.js
> +    pictureFilter.style.filter = 'brightness(' + getRandomInteger(MIN_BRIGHTNESS, MAX_BRIGHTNESS) + ')';
Исправлено

2020-10-20 10:22 UTC, Yougn commented on js/main.js
> +    pictureFilter.style.filter = 'blur(' + getLevelEffect() / 100 * 3 + 'px)';
Исправлено

2020-10-20 10:59 UTC, Yougn commented on js/main.js
> +
Исправлено

2020-10-20 11:07 UTC, Yougn commented on js/main.js
> +    var number = parseInt(fieldControl.value, 10);
Исправлено

2020-10-20 11:10 UTC, Yougn commented on js/main.js
> +    if (!textHashtagsValue[0].includes('#')) {
Исправлено

2020-10-20 11:20 UTC, Yougn commented on js/main.js
> +  var textLists = textHashtagsValue.toLowerCase().split(' ');
Исправлено

2020-10-20 11:21 UTC, Yougn commented on js/main.js
> +  var arraysHashtags = [];
вроде good

2020-10-20 11:26 UTC, Yougn commented on js/main.js
> +  for (var i = 0; i < textListsNumber; i++) {
Исправлено

2020-10-20 11:26 UTC, Yougn commented on js/main.js
> +    if (textListsNumber > NUMBER_HASHTAGS) {
Исправлено

2020-10-20 11:30 UTC, Yougn commented on js/main.js
> +      textHashtags.setCustomValidity('Один и тот же хэш-тег не может быть использован дважды');
Исправлено

2020-10-20 16:19 UTC, Yougn commented on js/main.js
> +    var isHashtagValid = validHashtag(textListsNumber[i]);
Исправлено

2020-10-20 16:20 UTC, Yougn commented on js/main.js
> +  var newFilter = pictureFilter.classList.item(1);
Исправлено

2020-10-20 16:25 UTC, Yougn commented on js/main.js
> +  if (pictureFilter.classList.contains('effects__preview--chrome')) {
Исправлено

2020-10-21 06:40 UTC, balesniy requested changes

2020-10-21 06:40 UTC, balesniy commented on js/main.js
> +  if (pictureFilter.classList.contains('effects__preview--' + currentFilter)) {
лишнее условие, текущий фильтр можно сразу снимать

2020-10-21 06:40 UTC, balesniy commented on js/main.js
> +  var slider = document.querySelector('.img-upload__effects');
поиск по селектору нужно вынести из функции

2020-10-21 06:40 UTC, balesniy commented on js/main.js
> +  var slider = document.querySelector('.img-upload__effects');
повторяется поиск элемента

2020-10-21 06:40 UTC, balesniy commented on js/main.js
> +  var hashtagList = textHashtagsValue.toLowerCase().split(' ');
массивы нужно назвать во множественном значении ((

2020-10-21 06:40 UTC, balesniy commented on js/main.js
> +  };
тут из функции можно выйти, цикл запускать уже не нужно

2020-10-21 06:40 UTC, balesniy commented on js/main.js
> +    var isHashtagValid = validHashtag(blockHashtgsNumber[i]);
blockHashtgsNumber это число тегов, не массив, а нам нужно проверять элемент массива

2020-10-21 07:00 UTC, Yougn commented on js/main.js
> +  var slider = document.querySelector('.img-upload__effects');
Исправлено

2020-10-21 07:01 UTC, Yougn commented on js/main.js
> +  var slider = document.querySelector('.img-upload__effects');
Исправлено

2020-10-21 07:02 UTC, Yougn commented on js/main.js
> +  var hashtagList = textHashtagsValue.toLowerCase().split(' ');
Исправлено

2020-10-21 07:03 UTC, Yougn commented on js/main.js
> +  };
Исправлено

2020-10-21 07:09 UTC, Yougn commented on js/main.js
> +  var hashtagList = textHashtagsValue.toLowerCase().split(' ');
so sorry

2020-10-21 07:10 UTC, Yougn commented on js/main.js
> +    var isHashtagValid = validHashtag(blockHashtgsNumber[i]);
Исправлено

2020-10-21 07:24 UTC, Yougn commented on js/main.js
> +  if (pictureFilter.classList.contains('effects__preview--' + currentFilter)) {
Исправлено

2020-10-21 11:35 UTC, balesniy requested changes

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +  var body = document.querySelector('body');
у тебя уже есть снаружи body

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +  if (currentFilter !== newFilter) {
лишняя проверка, при событии change будет всегда true - проверять нужно само значение currentFilter

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +  var newFilter = choise;
лишняя переменная

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +  var hashtagLists = textHashtagsValue.toLowerCase().split(' ');
тут хэштеги - hashtags не списки

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +  var blockHashtagElements = hashtagLists.length;
а тут количество hashtagsLength, не элементы

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +    var isHashtagValid = validHashtag(blockHashtagElements[i]);
var blockHashtagElements = hashtagLists.length; - в переменную записано число, не массив, типа 5, а у числа нет элементов, blockHashtagElements[i] не существует

2020-10-21 11:35 UTC, balesniy commented on js/main.js
> +    if (blockHashtagElements > NUMBER_HASHTAGS) {
проверку на количество тегов нужно вынести из цикла, проверить количество нужно до запуска цикла, на каждой итерации снова и снова проверять количество не нужно

2020-10-21 15:47 UTC, Yougn commented on js/main.js
> +  var body = document.querySelector('body');
Исправлено

2020-10-21 15:55 UTC, Yougn commented on js/main.js
> +  if (currentFilter !== newFilter) {
Исправлено

2020-10-21 15:58 UTC, Yougn commented on js/main.js
> +  var newFilter = choise;
Исправлено

2020-10-21 16:06 UTC, Yougn commented on js/main.js
> +  var hashtagLists = textHashtagsValue.toLowerCase().split(' ');
Исправлено

2020-10-21 16:16 UTC, Yougn commented on js/main.js
> +  var blockHashtagElements = hashtagLists.length;
Исправлено

2020-10-21 16:18 UTC, Yougn commented on js/main.js
> +    var isHashtagValid = validHashtag(blockHashtagElements[i]);
Исправлено

2020-10-21 16:30 UTC, Yougn commented on js/main.js
> +    if (blockHashtagElements > NUMBER_HASHTAGS) {
Исправлено

2020-10-22 10:17 UTC, balesniy commented on js/main.js
> +    if (blockHashtags.includes(hashtagsNumber[i])) {
hashtagsNumber это число, длина массива, не массив (((

2020-10-23 19:19 UTC, Yougn commented on js/main.js
> +    if (blockHashtags.includes(hashtagsNumber[i])) {
не пойму в какой плоскости мы общаемся) вроде исправлено

2020-10-23 19:52 UTC, merged