Module6 task2
Yougn/1138711-kekstagram-20 pull request #6
Opened 2020-11-11 19:29 UTC by Yougn

2020-11-12 13:37 UTC, balesniy commented on js/gallery.js
> +
`window.resultPicture = photos` чтобы до смены сортировки заработал selectPicture

2020-11-12 14:48 UTC, Yougn commented on js/gallery.js
> +
Исправлено

2020-11-14 12:00 UTC, balesniy approved these changes

2020-11-14 12:00 UTC, balesniy commented on js/gallery.js
> +    var photosArray = photos.slice();
название массивов

2020-11-14 12:00 UTC, balesniy commented on js/form.js
> +  var closeBannerError = function () {
повторяет closeBanner

2020-11-14 12:00 UTC, balesniy commented on js/gallery.js
> +      removePictures();
повторяется код  в ветках

2020-11-14 12:00 UTC, balesniy commented on js/gallery.js
> +    } else if (id === 'filter-default') {
айди фильтров нужно в константы

2020-11-14 12:00 UTC, balesniy commented on js/gallery.js
> +    window.resultPicture = filterPhotos(id);
массив

2020-11-15 14:29 UTC, Yougn commented on js/gallery.js
> +    var photosArray = photos.slice();
Исправлено

2020-11-15 14:53 UTC, Yougn commented on js/gallery.js
> +    } else if (id === 'filter-default') {
Исправлено

2020-11-15 14:55 UTC, Yougn commented on js/gallery.js
> +    window.resultPicture = filterPhotos(id);
Исправлено

2020-11-16 14:07 UTC, balesniy requested changes

2020-11-16 14:07 UTC, balesniy commented on js/picture.js
> +    mainPicture: mainPicture,
в названии свойств не должно быть названия объектов

2020-11-16 14:07 UTC, balesniy commented on js/picture.js
>            pictureComments.appendChild(commentsList[i]);
для множественной вставки нужен фрагмент

2020-11-16 14:07 UTC, balesniy commented on js/picture.js
>          var commentsList = comments.slice(0, number)
массив ((

2020-11-16 14:07 UTC, balesniy commented on js/picture.js
>          if (commentsList.length === photo.comments.length) {
тут не обязательно точное совпадение, number меняется дискретно

2020-11-16 18:45 UTC, merged

2020-11-16 19:08 UTC, Yougn commented on js/gallery.js
> +      removePictures();
Исправлено

2020-11-16 19:08 UTC, Yougn commented on js/form.js
> +  var closeBannerError = function () {
Исправлено

2020-11-16 19:12 UTC, Yougn commented on js/picture.js
>          var commentsList = comments.slice(0, number)
Исправлено

2020-11-16 19:45 UTC, Yougn commented on js/picture.js
>            pictureComments.appendChild(commentsList[i]);
Исправлено

2020-11-16 19:46 UTC, Yougn commented on js/picture.js
>            pictureComments.appendChild(commentsList[i]);
А почему именно он в данной ситуации?

2020-11-16 19:46 UTC, Yougn commented on js/picture.js
> +    mainPicture: mainPicture,
Вроде исправил

2020-11-16 20:18 UTC, balesniy commented on js/picture.js
>            pictureComments.appendChild(commentsList[i]);
потому что контейнер элементами заполняется прямо на странице

2020-11-16 20:21 UTC, Yougn commented on js/picture.js
> +    mainPicture: mainPicture,
Исправлено